/**
 * Renders the docs site's benchmark page from the committed summaries: what
 * is measured and how, the arms with their list prices, the newest matrix
 * per track, and the history of matrices. Generated, never hand-edited; the
 * root `check` fails when the page and `results/` disagree.
 */

import { renderTrack } from './render.ts';
import type { Summary } from './summary.ts';
import { TRACKS } from './tracks.ts';

const GENERATED_NOTICE = '{/* Generated by `pnpm bench docs` from packages/bench/results. Edit packages/bench/src/docs-page.ts instead. */}';

const money = (perMillion: number | undefined): string => (perMillion === undefined ? '-' : `$${perMillion.toFixed(2)}`);

/** The whole page; `summaries` newest first, empty when no matrix has run yet. */
export function renderDocsPage(summaries: readonly Summary[]): string {
  const latest = summaries[0];
  return [
    '---',
    'title: Benchmark',
    'description: E2E Bench runs the same agentic tasks across models and releases and publishes what each model passed, missed, invented, and cost.',
    '---',
    '',
    GENERATED_NOTICE,
    '',
    ...intro(),
    ...methodology(),
    ...(latest === undefined ? noResultsYet() : results(latest)),
    ...arms(latest),
    ...history(summaries),
    ...reproduce(),
  ].join('\n');
}

function intro(): string[] {
  return [
    'E2E Bench answers two questions with one dataset. Which model is good at',
    'agentic testing: the harness is held at one e2e release and the model is',
    'varied. And whether e2e itself is getting better: the model is held at the',
    'reference arm, the one the repository\'s own PR gate runs, and the release',
    'is varied. Every number below comes from a real run of the suites in this',
    'repository, with the trace cache off and no retries, so every model call is',
    'a measurement. The bench never gates a pull request.',
    '',
  ];
}

function methodology(): string[] {
  return [
    '## What is measured',
    '',
    '| Track | Suite | What a row means |',
    '| --- | --- | --- |',
    ...TRACKS.map((track) => `| \`${track.id}\` | \`${track.packageDir}\` | ${track.description} |`),
    '',
    '**Act.** One `agent.act` per scenario, then a deterministic check of the',
    'success message. Pass rate is over the scenarios that ran; reliability is the',
    'share of scenarios that passed in every repeat. Failure codes keep an honest',
    '`failed` verdict apart from a loop that never concluded or ran out of budget.',
    'Scenarios the grammar cannot finish yet are skipped and counted as harness',
    'gaps, never against the model.',
    '',
    '**Judgment.** `agent.assert` of the behavior a working product would show.',
    'On the eight planted-bug pages the assertion must fail: a failed assertion is',
    'a caught bug, a pass is a missed one. On working pages, the two trap pages',
    'included (they look broken and are not), the assertion must pass: a failed',
    'assertion is a false alarm. A test that never reached the judgment, a hung',
    'provider request for instance, is inconclusive and counts in neither cell.',
    '',
    '**Explore.** `e2e explore` against a bookshop with eleven planted defects.',
    'Recall is defects found over defects planted, matched by deterministic',
    'patterns. Findings that match no defect are judged once by a human and',
    'recorded in an adjudication file as real or not; precision is over those.',
    'The same exploration runs against the shop with every defect fixed, where',
    'every issue reported is a false positive by construction.',
    '',
    '**Cost and speed.** Every row carries model calls, actions, tokens in and',
    'out, the share of input served from the prompt cache, reasoning tokens, the',
    'cost the provider reported next to the same tokens at list price, wall time,',
    'and time outside harness work (observation, engine, policy). Compare dollars',
    'across vendors, not tokens: tokenizers differ by up to a third.',
    '',
    '<Note>',
    'A single repeat is a calibration, not a result. Rows are comparable within',
    'one task-set version and one e2e release only; the history lists both.',
    '</Note>',
    '',
  ];
}

function noResultsYet(): string[] {
  return ['## Results', '', 'No matrix has been published yet.', ''];
}

function results(latest: Summary): string[] {
  const lines = [
    '## Results',
    '',
    `Newest matrix: \`${latest.label}\`, e2e ${latest.provenance.e2eVersion} (\`${latest.provenance.commit.slice(0, 8)}\`), task set v${String(latest.taskSetVersion)}, ${String(latest.config.repeats)} repeat(s), ${latest.createdAt.slice(0, 10)}. Arms are named by their catalog id; the table under [Arms](#arms) maps them to model ids and prices.`,
    '',
  ];
  for (const track of latest.config.tracks) {
    const rows = latest.rows.filter((row) => row.track === track);
    if (rows.length === 0) continue;
    lines.push(`### ${track}`, '', ...renderTrack(track, rows), '');
  }
  const failed = latest.runs.filter((run) => run.error !== undefined);
  if (failed.length > 0) {
    lines.push('Runs that produced no report and are left out of the means:', '');
    for (const run of failed) lines.push(`- \`${run.arm}\` on \`${run.track}\` (repeat ${String(run.repeat)}): ${run.error ?? ''}`);
    lines.push('');
  }
  return lines;
}

function arms(latest: Summary | undefined): string[] {
  if (latest === undefined) return [];
  return [
    '## Arms',
    '',
    'Gateway model ids, exact and never a moving alias, with list prices in USD per million tokens on the day of the matrix.',
    '',
    '| arm | model | tier | input | output | cache read |',
    '| --- | --- | --- | --- | --- | --- |',
    ...latest.config.arms.map(
      (arm) =>
        `| ${arm.id}${arm.id === latest.config.referenceArm ? ' (reference)' : ''} | \`${arm.model}\` | ${arm.tier} | ${money(arm.pricing.input)} | ${money(arm.pricing.output)} | ${money(arm.pricing.cacheRead)} |`,
    ),
    '',
  ];
}

function history(summaries: readonly Summary[]): string[] {
  if (summaries.length === 0) return [];
  return [
    '## History',
    '',
    '| date | label | e2e | task set | arms | tracks | repeats |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...summaries.map(
      (summary) =>
        `| ${summary.createdAt.slice(0, 10)} | ${summary.label} | ${summary.provenance.e2eVersion} (\`${summary.provenance.commit.slice(0, 8)}\`) | v${String(summary.taskSetVersion)} | ${String(summary.config.arms.length)} | ${summary.config.tracks.join(', ')} | ${String(summary.config.repeats)} |`,
    ),
    '',
    'Every summary is a JSON file under `packages/bench/results/` in the repository, with the per-task outcome of every run.',
    '',
  ];
}

function reproduce(): string[] {
  return [
    '## Reproduce',
    '',
    'The bench is the `packages/bench` workspace package. It spawns the built `e2e` CLI once per arm, track, and repeat, each run against its own app instance, and scores the reports it leaves behind.',
    '',
    '```bash',
    'pnpm build && pnpm --filter @e2edev/web-benchmark run build',
    'AI_GATEWAY_API_KEY=... pnpm bench run --repeats 3 --label my-matrix',
    'pnpm bench report',
    '```',
    '',
    'Adding a model is one entry in `packages/bench/src/catalog.ts`; adding a task is a test in the suite it belongs to and a bump of the task-set version.',
    '',
  ];
}
