/**
 * The engine's roles and accessible names against the expectations the
 * axe-core test suite states for the same markup (`tests/conformance/axe-core/`).
 * Every target of every case is checked; what the engine reads differently
 * must be listed in `tests/conformance/expected.txt` with a reason, and a
 * listed case that now agrees fails too. `E2E_CROSSCHECK_UPDATE=1` rewrites
 * the file the way it rewrites the cross-check's.
 */

import { createRequire } from 'node:module';
import path from 'node:path';
import { chromium, type Browser, type Page } from 'playwright-core';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { CLOSED_SHADOW_ROOTS_INIT_SCRIPT } from '../../src/closed-shadow.ts';
import { captureTagged, MARKER, type Disagreement } from '../crosscheck/crosscheck.ts';
import { diffExpectations, keyOf, readExpectations, TODO_REASON, writeExpectations } from '../crosscheck/expectations.ts';

interface AxeCase {
  readonly html: string;
  readonly target: string | readonly string[];
  readonly role?: string | null;
  readonly accessibleText?: string | readonly string[];
}

const require = createRequire(import.meta.url);
const TABLES: Readonly<Record<string, readonly AxeCase[]>> = {
  'implicit-role': require('../conformance/axe-core/implicit-role.cjs') as AxeCase[],
  'accessible-text': require('../conformance/axe-core/accessible-text.cjs') as AxeCase[],
};
const EXPECTED = path.join(import.meta.dirname, '../conformance/expected.txt');
const HEADER = [
  '# Cases where the engine reads markup differently from what the axe-core suite expects, one per line:',
  '# page | oracle field | case target | ours <value> | theirs <value> | reason',
  '# Generated by E2E_CROSSCHECK_UPDATE=1; edit only the reasons. See tests/crosscheck/expectations.ts.',
].join('\n');
const UPDATE = process.env['E2E_CROSSCHECK_UPDATE'] === '1';

/**
 * The cases are markup without layout, and the tree lists only what has a
 * box: an empty element gets a one-pixel one, as the reader's own role tests
 * do, so a role is read rather than a zero-size element skipped.
 */
const EMPTY_BOXES = '<style>:empty { min-width: 1px; min-height: 1px }</style>';

/** axe spells an open shadow root as `<template shadow>`; this attaches each one, as Playwright's runner of these cases does. */
const SHADOW_TEMPLATES = `<script>
  for (const template of document.querySelectorAll('template[shadow]')) {
    template.parentElement.attachShadow({ mode: 'open' }).appendChild(template.content);
    template.remove();
  }
</script>`;

/** Roles the tree spells its own way, and the roles that mean "no role" to axe. */
const AS_ARIA: Readonly<Record<string, string>> = { image: 'img' };
const NO_ROLE = new Set(['generic', 'none', 'presentation', 'text']);

let browser: Browser;
let page: Page;
const seen = new Set<string>();
const pages = new Set<string>();

beforeAll(async () => {
  browser = await chromium.launch();
  const context = await browser.newContext();
  await context.addInitScript(CLOSED_SHADOW_ROOTS_INIT_SCRIPT);
  page = await context.newPage();
});

afterAll(async () => {
  await browser?.close();
});

const asList = <T,>(value: T | readonly T[]): readonly T[] => (Array.isArray(value) ? value : [value as T]);

describe('axe-core conformance', () => {
  for (const [table, cases] of Object.entries(TABLES)) {
    it(`${table}: every case`, { timeout: 300_000 }, async () => {
      const name = `axe: ${table}`;
      pages.add(name);
      let checked = 0;
      let targets = 0;
      for (const [index, entry] of cases.entries()) {
        await page.setContent(`<!doctype html><html lang="en"><head>${EMPTY_BOXES}</head><body>${entry.html}${SHADOW_TEMPLATES}</body></html>`);
        const { nodes, elements } = await captureTagged(page);
        try {
          const byId = new Map(nodes.map((node) => [node.ref.id, node]));
          const selectors = asList(entry.target);
          const texts = entry.accessibleText === undefined ? undefined : asList(entry.accessibleText);
          for (const [position, selector] of selectors.entries()) {
            targets += 1;
            const target = page.locator(selector).first();
            expect(await target.count(), `${table} #${index}: ${selector} matches nothing`).toBe(1);
            const id = await target.getAttribute(MARKER);
            const node = id === null ? undefined : byId.get(id);
            const label = `#${index} ${selector}`;
            const push = (field: string, ours: string, theirs: string) => {
              const disagreement: Disagreement = { oracle: 'axe', field, ours, theirs, node: label };
              seen.add(keyOf(name, disagreement));
            };
            if (entry.role !== undefined) {
              // A node the tree does not list has no role to the model either.
              const ours = node?.role === undefined || NO_ROLE.has(node.role) ? 'none' : (AS_ARIA[node.role] ?? node.role);
              const theirs = entry.role === null || entry.role === undefined || NO_ROLE.has(entry.role) ? 'none' : entry.role;
              if (ours !== theirs) push('role', ours, theirs);
              checked += 1;
            }
            if (texts !== undefined) {
              const ours = node === undefined ? '(not in tree)' : (node.name ?? '').replace(/\s+/g, ' ').trim();
              const theirs = (texts[position] ?? '').replace(/\s+/g, ' ').trim();
              if (ours !== theirs) push('name', ours, theirs);
              checked += 1;
            }
          }
        } finally {
          await Promise.all([...elements.values()].map((element) => element.dispose()));
        }
      }
      expect(checked, `${table} checked nothing`).toBeGreaterThan(0);
      expect(checked).toBe(targets);
    });
  }

  it('matches the expectations', () => {
    const expected = readExpectations(EXPECTED);
    if (UPDATE) {
      writeExpectations(EXPECTED, HEADER, expected, seen, pages);
      return;
    }
    const { unexpected, stale } = diffExpectations(expected, seen, pages);
    const todo = [...expected].filter(([, reason]) => reason === TODO_REASON).map(([key]) => key);
    expect({ unexpected, stale, todo }, 'rerun with E2E_CROSSCHECK_UPDATE=1 and review the diff of tests/conformance/expected.txt').toEqual({
      unexpected: [],
      stale: [],
      todo: [],
    });
  });
});
