/**
 * The engine's tree against Chrome's accessibility tree and Playwright's
 * `getByRole` on the fixture pages, and on every web-benchmark scenario when
 * `CROSSCHECK_BENCHMARK_URL` names a running benchmark app. Disagreements
 * must match `tests/crosscheck/expected.txt`; `E2E_CROSSCHECK_UPDATE=1`
 * rewrites it (see `tests/crosscheck/expectations.ts`).
 */

import path from 'node:path';
import { chromium, type Browser, type Page } from 'playwright-core';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { CLOSED_SHADOW_ROOTS_INIT_SCRIPT } from '../../src/closed-shadow.ts';
import { crossCheck } from '../crosscheck/crosscheck.ts';
import { diffExpectations, keyOf, readExpectations, TODO_REASON, writeExpectations } from '../crosscheck/expectations.ts';
import { FIXTURE_PAGES } from '../crosscheck/fixtures.ts';

const EXPECTED = path.join(import.meta.dirname, '../crosscheck/expected.txt');
const HEADER = [
  '# Known disagreements between the engine tree and Chrome or Playwright, one per line:',
  '# page | oracle field | role "name" | ours <value> | theirs <value> | reason',
  '# Generated by E2E_CROSSCHECK_UPDATE=1; edit only the reasons. See tests/crosscheck/expectations.ts.',
].join('\n');
const BENCHMARK = process.env['CROSSCHECK_BENCHMARK_URL'];
const UPDATE = process.env['E2E_CROSSCHECK_UPDATE'] === '1';

let browser: Browser;
let page: Page;
const seen = new Set<string>();
const pages = new Set<string>();

beforeAll(async () => {
  browser = await chromium.launch();
  const context = await browser.newContext();
  await context.addInitScript(CLOSED_SHADOW_ROOTS_INIT_SCRIPT);
  page = await context.newPage();
});

afterAll(async () => {
  await browser?.close();
});

/** Checks the page as loaded and records its disagreements under `name`. */
async function check(name: string): Promise<void> {
  const result = await crossCheck(page);
  expect(result.compared, `${name} compared no node`).toBeGreaterThan(0);
  pages.add(name);
  for (const disagreement of result.disagreements) seen.add(keyOf(name, disagreement));
}

describe('cross-check', () => {
  for (const fixture of FIXTURE_PAGES) {
    it(`fixture: ${fixture.name}`, async () => {
      await page.setContent(`<!doctype html><html lang="en"><body>${fixture.html}</body></html>`);
      await check(`fixture: ${fixture.name}`);
    });
  }

  describe.skipIf(BENCHMARK === undefined)('web-benchmark scenarios', () => {
    it('every scenario', { timeout: 600_000 }, async () => {
      await page.goto(BENCHMARK!);
      const slugs = await page.locator('a[href^="/e/"]').evaluateAll((links) =>
        [...new Set(links.map((link) => new URL((link as HTMLAnchorElement).href).pathname.slice('/e/'.length)))]);
      expect(slugs.length).toBeGreaterThan(0);
      for (const slug of slugs.toSorted()) {
        await page.goto(new URL(`/e/${slug}`, BENCHMARK).href, { waitUntil: 'networkidle' });
        await check(`benchmark: ${slug}`);
      }
    });
  });

  it('matches the expectations', () => {
    const expected = readExpectations(EXPECTED);
    if (UPDATE) {
      writeExpectations(EXPECTED, HEADER, expected, seen, pages);
      return;
    }
    const { unexpected, stale } = diffExpectations(expected, seen, pages);
    const todo = [...expected].filter(([key, reason]) => pages.has(key.slice(0, key.indexOf(' | '))) && reason === TODO_REASON).map(([key]) => key);
    expect({ unexpected, stale, todo }, 'rerun with E2E_CROSSCHECK_UPDATE=1 and review the diff of tests/crosscheck/expected.txt').toEqual({
      unexpected: [],
      stale: [],
      todo: [],
    });
  });
});
